# HW1 B06109022

### part 1

In [148]:
# install package
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

使用 python 語言 並載入 numpy 跟 sklearn 中 TfidfVectorizer 以及 cosine_similarity 套件

In [149]:
#load the data
doc=[]

for i in range(1,1096):
    f = open('PA1-data/'+str(i)+'.txt')
    txt=''
    for j in f.readlines():
        txt+=j.strip('\n').lower() 
        
    doc.append(txt)
    
    f.close()

讀入題目文字檔案並將他們全部都移除換行符號、轉為小寫，依序放入doc這個list裡面

In [151]:
len(doc)

1095

確認doc的內容，以及是否將1095個題目文字檔案全部放入doc中。

In [152]:
Tfidf_vectorizer = TfidfVectorizer(lowercase=True,stop_words='english')
Tfidf_vector = Tfidf_vectorizer.fit_transform(doc)
vector = Tfidf_vector.toarray()

In [153]:
vector

array([[0.        , 0.03906019, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.04029398, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.07294386, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [154]:
vector.shape

(1095, 19130)

使用sklearn 中 TfidfVectorizer套件，將doc轉換成Tfidf_vector

### part 2

In [155]:
for i in range(1,1096):
    np.savetxt('PA1-data_vec/vec'+str(i)+'.txt', vector[i-1])

使用numpy套件，將Tfidf_vector依序存成對應的vector.text檔

### part 3

使用numpy套件，將vector1跟vector2讀入，以利後續使用 sklearn 中 cosine_similarity 套件，來測量 cosine similarity

In [156]:
vec1 = np.loadtxt('PA1-data_vec/vec1.txt')

In [157]:
vec1

array([0.        , 0.03906019, 0.        , ..., 0.        , 0.        ,
       0.        ])

In [158]:
vec1.shape

(19130,)

In [159]:
vec2 = np.loadtxt('PA1-data_vec/vec2.txt')

In [160]:
vec2

array([0., 0., 0., ..., 0., 0., 0.])

In [161]:
vec2.shape

(19130,)

In [162]:
TFIDF_vectors=[vec1,vec2]

In [163]:
cosine_similarity(TFIDF_vectors,TFIDF_vectors)

array([[1.        , 0.19991362],
       [0.19991362, 1.        ]])

In [164]:
cosine_similarity(TFIDF_vectors,TFIDF_vectors)[0][1]

0.19991361508978645

最後 vector1 跟 vector2 的 cosine similarity 為 0.1999